const stations = [
  { id: 1, name: "Sahibabad", line: "Blue Line" },
  { id: 2, name: "Vasundhara", line: null },
  { id: 3, name: "Shakti Khand", line: null },
  { id: 4, name: "DPS Indirapuram", line: null },
  { id: 5, name: "Vaibhav Khand", line: null },
  { id: 6, name: "Noida Electronic City", line: null },
  { id: 7, name: "Noida Sector 62", line: null },
  { id: 8, name: "Noida Sector 59", line: null },
  { id: 9, name: "Noida Sector 61", line: null },
  { id: 10, name: "Noida Sector 52", line: "Aqua Line" },
  { id: 11, name: "Noida Sector 34", line: null },
  { id: 12, name: "Mohan Nagar", line: "Red Line" },
  { id: 13, name: "Noida City Centre", line: null },
  { id: 14, name: "Indira Colony", line: null },
  { id: 15, name: "Golf Course", line: null },
  { id: 16, name: "Sahibabad", line: null },
  { id: 17, name: "Botanical Garden", line: "Magenta Line" },
  { id: 18, name: "Prahlad Garhi", line: null },
  { id: 19, name: "Noida Sector 18", line: null },
  { id: 20, name: "Vaishali", line: null },
  { id: 21, name: "Noida Sector 16", line: null },
  { id: 22, name: "Kaushambi", line: null },
  { id: 23, name: "Noida Sector 15", line: null },
  { id: 24, name: "Anand Vihar Terminal railway station", line: "Pink Line" },
  { id: 25, name: "Swami Vivekanand ISBT", line: "Pink Line" },
  { id: 26, name: "Anand Vihar", line: "Pink Line" },
  { id: 27, name: "New Ashok Nagar", line: null },
  { id: 28, name: "Karkarduma", line: "Pink Line" },
  { id: 29, name: "Mayur Vihar Extension", line: null },
  { id: 30, name: "Preet Vihar", line: null },
  { id: 31, name: "Mayur Vihar-I", line: "Pink Line" },
  { id: 32, name: "Nirman Vihar", line: null },
  { id: 33, name: "Nizamuddin Bridge", line: null },
  { id: 34, name: "Laxmi Nagar", line: null },
  { id: 35, name: "Akshardham", line: null },
  { id: 36, name: "Yamuna Bank", line: null },
  { id: 37, name: "Yamuna River", line: null },
  { id: 38, name: "Indraprastha", line: "Green Line, Magenta Line" },
  { id: 39, name: "Ring Road", line: null },
  { id: 40, name: "Indian Railways", line: null },
  { id: 41, name: "Supreme Court", line: null },
  { id: 42, name: "Tilak Marg/ITO", line: null },
  { id: 43, name: "Mandi House", line: "Violet Line" },
  { id: 44, name: "Barakhamba Road", line: null },
  { id: 45, name: "Rajiv Chowk", line: "Yellow Line" },
  { id: 46, name: "Ramakrishna Ashram Marg", line: "Magenta Line" },
  { id: 47, name: "Jhandewalan", line: null },
  { id: 48, name: "Ridge Road", line: null },
  { id: 49, name: "Karol Bagh", line: null },
  { id: 50, name: "Rajendra Place", line: null },
  { id: 51, name: "Patel Nagar", line: null },
  { id: 52, name: "Shadipur", line: null },
  { id: 53, name: "Kirti Nagar", line: "Green Line" },
  { id: 54, name: "Satguru Ram Singh Marg", line: null },
  { id: 55, name: "Moti Nagar", line: null },
  { id: 56, name: "Ramesh Nagar", line: null },
  { id: 57, name: "Rajouri Garden", line: "Pink Line" },
  { id: 58, name: "Tagore Garden", line: null },
  { id: 59, name: "Subhash Nagar", line: null },
  { id: 60, name: "Tilak Nagar", line: null },
  { id: 61, name: "Janakpuri East", line: null },
  { id: 62, name: "Outer Ring Road", line: null },
  { id: 63, name: "Janakpuri West", line: "Magenta Line" },
  { id: 64, name: "Uttam Nagar East", line: null },
  { id: 65, name: "Uttam Nagar West", line: null },
  { id: 66, name: "Nawada", line: null },
  { id: 67, name: "Dwarka Mor", line: null },
  { id: 68, name: "Dwarka", line: "Grey Line" },
  { id: 69, name: "Dwarka Sector 14", line: null },
  { id: 70, name: "Dwarka Sector 13", line: null },
  { id: 71, name: "Dwarka Sector 12", line: null },
  { id: 72, name: "Dwarka Sector 11", line: null },
  { id: 73, name: "Dwarka Sector 10", line: null },
  { id: 74, name: "Dwarka Sector 9", line: "Green Line" },
  { id: 75, name: "Dwarka Sector 8", line: null },
  { id: 76, name: "Dwarka Sector 21", line: "Airport Express" },
  { id: 77, name: "Dwarka Sector 26", line: null },
  { id: 78, name: "Bijwasan", line: null },
  { id: 79, name: "Kapashera", line: null },
];

export default stations;
